### ISSUE TITLE
OTP token description list broken when token without description is added

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/noggin#228]
PR #213 made the OTP token description not mandatory when generating a new OTP token. And creating a new OTP token without a description does indeed work. 

However, if you add more two or more  tokens, any of which do not have a description defined, the user/<username>/settings/otp/ page fails with the following error:

```
Traceback (most recent call last):
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/whitenoise/base.py", line 86, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.cache/pypoetry/virtualenvs/noggin-vs8V2ZPt-py3.7/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/noggin/utility/__init__.py", line 33, in fn
    return f(*args, **kwargs, ipa=ipa)
  File "/vagrant/noggin/utility/__init__.py", line 58, in fn
    return f(*args, **kwargs)
  File "/vagrant/noggin/controller/user.py", line 174, in user_settings_otp
    tokens.sort(key=lambda t: t.description)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by ryanlerch** [comment]
**Acceptance Criteria**
* user can add an OTP token without a description, and the OTP list page doesnt crash anymore.

**Definition of Done**
* All of the above works
* Unit tests for this specific case is written
* unit tests have 100% coverage
* CI passes
