### ISSUE TITLE
do not allow upper case login's to work

### ISSUE THREAD

**Issue by nirik** [fedora-infra/noggin#594]
noggin apparently lets me login as:
kevin
Kevin
KeVIN
However, ipsilon/ipa will fail to authenticate any of these except the all lower case one. 
We should probibly reject any logins with upper case and tell the user to try lower case...

**Comment by nirik** [comment]
Seems ipa web also allows any mixed case... and 'ipa user-show KeVIN' matches 'kevin'
So, I guess it's just ipsilon here thats not working with mixed case...

**Comment by abompard** [comment]
Yeah I'd rather lowercase the username field in Noggin than try to support mixed case in Ipsilon.

**Comment by nirik** [comment]
Well, it's kind of a mess here, because if noggin just lowercases the login, but ipsilon doesn't, people are going to fail to authenticate. ;( 
I'm fine with lower casing everything, but it should be everything then. Perhaps there's some options with the ipa connector ipsilon is using?

**Comment by jossperdomo** [comment]
Is this issue related to #573?

**Comment by abompard** [comment]
No it's unrelated, I believe.

**Comment by nirik** [comment]
Also, this breaks on password resets. 
If foobar tries to reset their password and they login as 'Foobar' noggin correctly sends them a reset token, but then when they click on it they get a 500 from noggin:

```
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/src/noggin/controller/password.py", line 206, in forgot_password_change
    lock.delete()
  File "/opt/app-root/src/noggin/utility/password_reset.py", line 30, in delete
    os.remove(self._get_file_path())
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/noggin-pw-reset/foobar'
```
Because of course the directory is 'Foobar'

**Comment by abompard** [comment]
This is #573, for which the fix has just been merged.
